ALTER TABLE Form
ADD FOREIGN KEY (reader_ticket_id) REFERENCES Reader_ticket (id) ON DELETE CASCADE,
ADD FOREIGN KEY (book_id) REFERENCES Book (id) ON DELETE CASCADE;

ALTER TABLE BookAuthor
ADD FOREIGN KEY (book_id) REFERENCES Book (id) ON DELETE CASCADE,
ADD FOREIGN KEY (author_id) REFERENCES Author (id) ON DELETE CASCADE;

ALTER TABLE BookGenre
ADD FOREIGN KEY (book_id) REFERENCES Book (id) ON DELETE CASCADE,
ADD FOREIGN KEY (genre_id) REFERENCES Genre (id) ON DELETE CASCADE;